baseurl = "http://power-libraries.github.io"
languageCode = "en-us"
title = "Power Libraries"
theme = "bootie-docs"
copyright = "Copyright (c) 2015, Manuel Hegner; All rights reserved."

[params]
	noCategoryLink = true
	repositoryUrl = "https://github.com/power-libraries/power-libraries"
	description = "making Java simpler"
	
	[params.mainMenu.iopower]
		url="iopower"
		name="IO Power"	