baseurl: 'http://power-libraries.github.io'
languageCode: en-us
title: Power Libraries
theme: bootie-docs
copyright: 'Copyright (c) 2019, Manuel Hegner; All rights reserved.'
enableGitInfo: true
frontmatter:
  date: :git
params:
  noCategoryLink: true
  repositoryUrl: 'https://github.com/power-libraries/power-libraries'
  description: making Java simpler
menu:
  main:
    - url: iopower
      name: IO Power
