version: 2.1
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run:
          name: submodules
          command: git submodule update --recursive --init
      - run: hugo
  deploy:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run:
          name: submodules
          command: git submodule update --recursive --init
      - add_ssh_keys:
          fingerprints:
            - "1b:68:30:58:84:46:f4:bd:6d:11:3a:a5:e2:f2:d7:75"
      - run: hugo
      - run: 
          name: deploy to master
          command: |
            git clone https://github.com/power-libraries/power-libraries.github.io.git dep/
            cd dep
            git checkout master
            rm -rf *
            cp -r /root/project/public/* ./
            git config user.email "50981256+power-libraries-bot@users.noreply.github.com"
            git config user.name "power-libraries-bot"
            git add *
            git commit --message "Update of page through $CIRCLE_SHA1"
            git push
    
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - deploy:
          filters:
            branches:
              only: sources