version: 2.1
docker:
  - image: cibuilds/hugo:latest
jobs:
  build:
    steps:
      - checkout
      - run: hugo
  deploy:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "1b:68:30:58:84:46:f4:bd:6d:11:3a:a5:e2:f2:d7:75"
      - run: |
          mkdir dep
          git clone git@github.com:power-libraries/power-libraries.github.io.git dep/
          cd dep
          git checkout master
          rm -rf *
          cp -r ../public/* ./
          git config user.email "50981256+power-libraries-bot@users.noreply.github.com"
          git config user.name "power-libraries-bot"
          git commit --message "Update of page through $CIRCLE_SHA1"
          git push
    
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: sources